### PR TITLE
Fix typo with `option.startswith` in SCIP API

### LINKED ISSUE #626: AttributeError: 'str' object has no attribute 'starts_with' in SCIP solver
Details for the issue
--------------------

#### What did you do?

Solve a problem with the `SCIP_CMD` solver, with `options=["set presolving emphasis aggressive", "set heuristics emphasis aggressive"]`.

#### What did you expect to see?

The options are added as CLI parameters to the SCIP call.

#### What did you see instead?

```
    status = solver.actualSolve(self, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.cache/pypoetry/virtualenvs/optimizer--RycKOkC-py3.11/lib/python3.11/site-packages/pulp/apis/scip_api.py", line 151, in actualSolve
    if option.starts_with("-"):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'starts_with'. Did you mean: 'startswith'?
```

Looks like we just have to replace `starts_with` with `startswith` in this line:
<https://github.com/coin-or/pulp/blob/006753076be18ee857339d333a5db11e599f21a2/pulp/apis/scip_api.py#L151>

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: (Pop!_OS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.11

#### I installed PuLP via:

- [ ] pypi (python -m pip install pulp)
- [ ] github (python -m pip install -U git+https://github.com/coin-or/pulp)
- [x] Other: Poetry, using GitHub with `rev="006753076be18ee857339d333a5db11e599f21a2"`

#### Did you also

- [x] Tried out the latest github version: https://github.com/coin-or/pulp
- [x] Searched for an existing similar issue: https://github.com/coin-or/pulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20

### PR DESCRIPTION
**Pull request by TimJentzsch**
Fixes #626.

Changes `option.starts_with` to `option.startswith` to fix an `AttributeError`.

### CODE REVIEW

**Comment by pchtsp** [comment]
Thanks! Could you please add a unit test to be sure this error doesn't happen again? Thanks!

**Comment by TimJentzsch** [comment]
> Thanks! Could you please add a unit test to be sure this error doesn't happen again? Thanks! 

I think right now this particular function is quite hard to test as it seems to access the file system, call the solver and such.
This would all have to be mocked to make it reproducible.

Perhaps the construction of the command list should be moved into its own function which is easier to test.

**Comment by TimJentzsch** [comment]
@pchtsp I refactored a bit and added tests which should catch the error.
Please let me know if this works for you :)

**Comment by TimJentzsch** [comment]
@pchtsp Is there anything I can do to drive this forward? :)

**Comment by pchtsp** [comment]
Hello I just checked. I'm not sure why there are that many changes when the title of the PR is "fix typo with option.startswith". Also, the tests are currently done in `pulp/tests/test_pulp.py`
For example, you can directly add the test methods to:
https://github.com/coin-or/pulp/blob/006753076be18ee857339d333a5db11e599f21a2/pulp/tests/test_pulp.py#L1464-L1467

So no need to create a new file to test APIs.

Thanks

**Comment by TimJentzsch** [comment]
Thank you, I moved the tests in the `test_pulp` file.

The other changes are a refactor to be able to write the tests properly.
The `actualSolve` function accessed the disk, so I pulled out the command building functionality to be able to test it in isolation.

**Comment by TimJentzsch** [comment]
@pchtsp Is there anything else I can do to improve this PR? :)

**Comment by pchtsp** [comment]
Hey sorry for taking so much time to answer. And thanks for all the work.
I don't think the refactoring is needed to be able to test the solver. After all, we already test all solvers that access the file system and it works fine.

The more changes there are in the PR, the harder is to review it. I would recommend to just do the minimal changes (I understand the change should just involve 1 line, even one character). And then add the tests that make it fail before and succeed now.

Thanks again and sorry for all the back and forth.

**Comment by pchtsp** [comment]
I'm closing as the issue was solved in this commit: https://github.com/coin-or/pulp/commit/787973b02506379475ffba847a2c3d843aca53ce

**Pull request closed without merging**
