### PR TITLE
Fix 508: does not crash when parsing mipopt solutions

### PR DESCRIPTION
**Pull request by thiagojobson**
The problem described in #508 is because solutions returned by CPLEX's mipopt solver lack the `dual` and `reducedCost` fields in the xml file.
I added try/catch so it does not crash anymore, but I'm not sure if, in this case, values should be set to `None` or `0`.

### CODE REVIEW

**Comment by thiagojobson** [comment]
Hello 👋, any chance this gets reviewed?
The checks failed due to unrelated issues.

**Comment by pchtsp** [comment]
Thanks for the contribution! And sorry for the delay response :  )

Could you please merge de master branch? the python version issues are already fixed there. 

Also, could you please add some unit test that failed previously and now passes with these changes? I think there's no present way to use a cplex license during unittests. But it could suffice to add a cplex test solution file to the repo and use it to run the tests.

**Comment by pchtsp** [comment]
thanks again. I does look good. 
I just have one small caveat. The place where you put the test *is* the most intuitive. Unfortunately, since it "requires" having the solver CPLEX_CMD, it will not be run in github. One way of going around this would be to (1) change the `readsol` method to  be static and (2) move the test somewhere else (I'm not 100% sure where, though). What do you think?

**Comment by thiagojobson** [comment]
Thanks @pchtsp !

I'm afraid that as I'm trying do add your suggestions I started to get the same problems in the workflow which seems to be unrelated to this PR.

**Comment by thiagojobson** [comment]
Hello @pchtsp,

I've added a test case and looks like it is is running and passing.

I think there's no need to make `readsol` static [unless I'm missing something?] because we can always instantiate CPLEX_CM and normally call `readsol` even though CPLEX isn't present.

**Pull request merged**
