### PR TITLE
Call SCIP from path defined in config file

### PR DESCRIPTION
**Pull request by roessig**
SICP is currently not found although specified in the config file.

### CODE REVIEW

**Comment by pchtsp** [comment]
Thanks for the help.
1. Is there any difference between using `'%s' % self.path` and just `self.path` ?
2. Could you please resolve the conflicts so we can merge this?

Thanks again

**Comment by roessig** [comment]
I think it did not work with just `self.path`, but cannot say why anymore. As far as I can see I cannot resolve the conflict, as I don't have the permission.

**Comment by pchtsp** [comment]
You need to merge the pulp master into your branch and correct the errors, then do a push to your fork.

**Comment by pchtsp** [comment]
Or just create a clean new pull request from the current master.

**Comment by pchtsp** [comment]
I'm closing this but please create a new PR with the change.

**Pull request closed without merging**
