### PR TITLE
Implementing TimeLimit for highspy

### PR DESCRIPTION
**Pull request by apschmidt**
Time limit was ignored in previous version for highspy, adding timeLimit functionality.

### CODE REVIEW

**Comment by apschmidt** [comment]
Seems to be an issue with ubuntu highspy implementation since Windows passes all tests

**Comment by pchtsp** [comment]
Mmm strange. Maybe you can check with the highs solver developers? Also, can you sign the cla? Thanks a lot for the contribution.

**Comment by MLopez-Ibanez** [comment]
> Seems to be an issue with ubuntu highspy implementation since Windows passes all tests

Looking at the logs, it seems highspy is not install nor tested for Windows so that would explain it.

**Comment by pchtsp** [comment]
It doesn't seem to pass the tests because the `timeLimit` check fails in Ubuntu actually. Are you sure it works?
image

**Comment by pchtsp** [comment]
I've merged the other PR #641 which addresses the issues with checking the timelimit in this one. Thanks for the work though!

**Pull request closed without merging**
