### PR TITLE
Fix issue #133: avoid file naming collisions by using uuids instead of pids

### PR DESCRIPTION
**Pull request by s-c-e**
Hi Stu - I'm a big PuLP fan and figured I could help with this file naming problem (#133 - and I've had the same problem come up in the past). Would you be okay to switch from pids to uuids?

### CODE REVIEW

**Comment by s-c-e** [comment]
Per your notes on another PR, I've removed Python 3.2 from the Travis CI file.

**Comment by s-c-e** [comment]
@stumitchell do you think this will fix the issue, or should I try something else?

**Comment by stumitchell** [comment]
No it is good sorry to take so long to put in it. I'll be doing a new release soon

**Comment by HySoaKa** [comment]
Thank you for your pr !!

**Pull request merged**
