### PR TITLE
Update pulp.py

### PR DESCRIPTION
**Pull request by jakedaford**
Current code currently overwrites constant in lhs with negative of rhs instead of subtracting rhs... seems like a bug

### CODE REVIEW

**Comment by jakedaford** [comment]
Just to include an example

```
>>> import pulp
>>> x = pulp.LpVariable('x')
>>> expr = pulp.LpAffineExpression({x: 1}, constant=3)
>>> c = pulp.LpConstraint(e=expr, rhs=5)
>>> c
1*x + -5 = 0
```

**Comment by stumitchell** [comment]
Interesting, I never used the constant arguement on lpAffineExpression.
I suspect you are right, Will ponder this for a bit, do you have a usecase or were you just looking at the code.

**Comment by jakedaford** [comment]
In example problems about costs, we could have
cost_run_machine_1 = 100 + 50x ($100 to start it up then $50 an hour)
cost_run_machine_n....
total_cost = sum(costs) <= 5,000

Also, even if the AffineExpression wasn't instantiated with a constant it could pick one up along the way... basically, as written, the user must "collect constant terms" before creating constraints.

**Comment by stumitchell** [comment]
can you add a test for this in https://github.com/coin-or/pulp/blob/master/src/pulp/tests.py

**Comment by jakedaford** [comment]
will do, but probably won't be til the weekend or so

**Comment by dinever** [comment]
Hi @stumitchell, thanks for merging this! Would you mind bumping the version on https://pypi.org/project/PuLP/ once you get a chance? Thanks a lot!

**Comment by stumitchell** [comment]
Should be up now give it a go

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by dinever** [comment]
thanks a lot!

**Pull request merged**
