### PR TITLE
Sphinx config

### LINKED ISSUE #387: Switch docs theme to sphinx_rtd_theme
Describe the new feature
--------------------------
At the moment the docs for PuLP are built using sphinx_glpi_theme.

This theme is an extension of sphinx_rtd_theme, to include some features such as a fancybox JS script (for displaying images) as well as some minor aesthetic changes (such as prev/next buttons at top of page in addition to bottom of page).

Reasons to switch to sphinx_rtd_theme:

- sphinx_glpi_theme is relatively obscure.   It has been downloaded ~38K times whereas sphinx_rtd_theme has ~32M downloads.
- sphinx_rtd_theme is actively maintained, whereas sphinx_glpi_theme is not
- since sphinx_glpi_theme is based on sphinx_rtd_theme, they have almost identical aesthetics and functionality
- the main difference between the two - the fancybox JS script - does not look like it is used by PuLP docs

I'm happy to submit pull request if the decision is made to switch

Additional info
---------------
Please answer these questions before submitting your feature request.

### PR DESCRIPTION
**Pull request by venaturum**
closes #387

@pchtsp are the docs published via an automated pipeline?

### CODE REVIEW

**Comment by pchtsp** [comment]
Hey, I'll check this tomorrow / sunday. No, the docs are not published automatically. Do you want to try to get a github action that publishes them? They need to be pushed to the `gh-pages` branch every time there's a new pulp version published (i.e., a new tag in git), I guess. You can copy the one we use to publish to pypi: https://github.com/coin-or/pulp/blob/master/.github/workflows/pythonpackage.yml

**Comment by pchtsp** [comment]
Thanks, I recompiled the docs and they look good (the same, as far as I can tell).

Just a couple of things:

1. Could you move the `docs/docs-requirements.txt` file to the root folder and call it `requirements-dev.txt`?
2. Do you think you can do the integration with github actions?
2. Could you add a couple of lines to the README to tell how to build the docs?

Something on the lines of:


Building the documentation:

```
cd pulp
pip3 install -r requirementes-dev.txt
mkdir ./../../pulp-or-docs
make html
```

Thanks again.

**Comment by venaturum** [comment]
No worries.  I'll do the github actions as a separate pull request.

While I'm editing README, we should change (or remove) the email address listed for JS Roy.  The jeannot.org domain no longer exists and redirects to "high risk websites".  I've tried to source an alternate address and found jean-sebastien.roy@edf.fr but I suspect it is also probably outdated.   Academic literature for JS dries up around 2007 so it's hard to know if he's still active.  Couldn't find him on linkedin either.

**Comment by pchtsp** [comment]
Hello again! Did you have time to make the changes? that way I can go and merge the PR. thanks!

**Comment by venaturum** [comment]
Hey Franco, see what you think.

I've left the JS Roy email issue alone, that can always be fixed later if needed.

I'm keen to give the Github Actions a go, but currently prepping a proposal for PyCon so might postpone it a couple of weeks.

**Comment by venaturum** [comment]
Potentially closes #328

**Comment by stumitchell** [comment]
I have hear from 3rd parties that JS Roy passed away around that time hence why I became the maintainer.

Please remove the email but make sure he is kept in any authorship list.

Probably remove my email as well as we have github now to sort that out.

> No worries. I'll do the github actions as a separate pull request.
> 
> While I'm editing README, we should change (or remove) the email address listed for JS Roy. The jeannot.org domain no longer exists and redirects to "high risk websites". I've tried to source an alternate address and found [jean-sebastien.roy@edf.fr](mailto:jean-sebastien.roy@edf.fr) but I suspect it is also probably outdated. Academic literature for JS dries up around 2007 so it's hard to know if he's still active. Couldn't find him on linkedin either.

**Comment by venaturum** [comment]
No worries.  Pushing a commit that removes all emails from licensing and copyright.

I have not touched the emails listed in doc\source\Authors.txt

**Pull request merged**
