### PR TITLE
adding Xpress solver config support

### PR DESCRIPTION
**Pull request by fmars**
This adds parameter control to PuLP interface to the Xpress optimization solver which makes it more convenient to use Xpress solver in PuLP. And it grants PuLP the ability to fully control and config Xpress solver. Use Sudoku Problem as an example which configs Xpress solver by  
```
solver = pulp.XPRESS(msg=1, maxSeconds=5, options=["NODESELECTION=1", "HEURDEPTH=5"])
prob.solve(solver)
```
```
Sudoku.py

# A list of strings from "1" to "9" is created
Sequence = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

# The Vals, Rows and Cols sequences all follow this form
Vals = Sequence
Rows = Sequence
Cols = Sequence

# The boxes list is created, with the row and column index of each square in each box
Boxes =[]
for i in range(3):
    for j in range(3):
        Boxes += [[(Rows[3*i+k],Cols[3*j+l]) for k in range(3) for l in range(3)]]

# The prob variable is created to contain the problem data
prob = LpProblem("Sudoku Problem",LpMinimize)

# The problem variables are created
choices = LpVariable.dicts("Choice",(Vals,Rows,Cols),0,1,LpInteger)

# The arbitrary objective function is added
arb = LpVariable("arbitrary var", 0)
prob += arb, "Arbitrary Objective Function"

# A constraint ensuring that only one value can be in each square is created
for r in Rows:
    for c in Cols:
        prob += lpSum([choices[v][r][c] for v in Vals]) == 1, ""

# The row, column and box constraints are added for each value
for v in Vals:
    for r in Rows:
        prob += lpSum([choices[v][r][c] for c in Cols]) == 1,""

    for c in Cols:
        prob += lpSum([choices[v][r][c] for r in Rows]) == 1,""

    for b in Boxes:
        prob += lpSum([choices[v][r][c] for (r,c) in b]) == 1,""

# The starting numbers are entered as constraints
prob += choices["5"]["1"]["1"] == 1,""
prob += choices["6"]["2"]["1"] == 1,""
prob += choices["8"]["4"]["1"] == 1,""
prob += choices["4"]["5"]["1"] == 1,""
prob += choices["7"]["6"]["1"] == 1,""
prob += choices["3"]["1"]["2"] == 1,""
prob += choices["9"]["3"]["2"] == 1,""
prob += choices["6"]["7"]["2"] == 1,""
prob += choices["8"]["3"]["3"] == 1,""
prob += choices["1"]["2"]["4"] == 1,""
prob += choices["8"]["5"]["4"] == 1,""
prob += choices["4"]["8"]["4"] == 1,""
prob += choices["7"]["1"]["5"] == 1,""
prob += choices["9"]["2"]["5"] == 1,""
prob += choices["6"]["4"]["5"] == 1,""
prob += choices["2"]["6"]["5"] == 1,""
prob += choices["1"]["8"]["5"] == 1,""
prob += choices["8"]["9"]["5"] == 1,""
prob += choices["5"]["2"]["6"] == 1,""
prob += choices["3"]["5"]["6"] == 1,""
prob += choices["9"]["8"]["6"] == 1,""
prob += choices["2"]["7"]["7"] == 1,""
prob += choices["6"]["3"]["8"] == 1,""
prob += choices["8"]["7"]["8"] == 1,""
prob += choices["7"]["9"]["8"] == 1,""
prob += choices["3"]["4"]["9"] == 1,""
prob += choices["1"]["5"]["9"] == 1,""
prob += choices["6"]["6"]["9"] == 1,""
prob += choices["5"]["8"]["9"] == 1,""

# The problem data is written to an .lp file
prob.writeLP("Sudoku.lp")

solver = pulp.XPRESS(msg=1, maxSeconds=5, options=["NODESELECTION=1", "HEURDEPTH=5"])
prob.solve(solver)

# The status of the solution is printed to the screen
print "Status:", LpStatus[prob.status]

# A file called sudokuout.txt is created/overwritten for writing to
sudokuout = open('sudokuout.txt','w')

# The solution is written to the sudokuout.txt file
for r in Rows:
    if r == "1" or r == "4" or r == "7":
                    sudokuout.write("+-------+-------+-------+\n")
    for c in Cols:
        for v in Vals:
            if value(choices[v][r][c])==1:

                if c == "1" or c == "4" or c =="7":
                    sudokuout.write("| ")

                sudokuout.write(v + " ")

                if c == "9":
                    sudokuout.write("|\n")
sudokuout.write("+-------+-------+-------+")
sudokuout.close()

# The location of the solution is give to the user
print "Solution Written to sudokuout.txt"
```

**Output (log was generated since msg=1)**
```
[~/fjc/Pulp] python simple.py
FICO Xpress-Optimizer 64-bit v28.01.04 (Hyper capacity)
(c) Copyright Fair Isaac Corporation 1983-2015. All rights reserved

Reading Problem /2416086-pulp
Problem Statistics
         353 (      0 spare) rows
         730 (      0 spare) structural columns
        2945 (      0 spare) non-zero elements
Global Statistics
         729 entities        0 sets        0 set members
Minimizing MILP /2416086-pulp
Original problem has:
       353 rows          730 cols         2945 elements       729 globals
Presolved problem has:
         0 rows            0 cols            0 elements         0 globals
LP relaxation tightened
Will try to keep branch and bound tree memory usage below 28.2Gb
Starting concurrent solve with dual

  Concurrent solve, 0s
         Dual
   objective    dual inf
       dual crash
 D   .0000000   .0000000
------- optimal --------
Optimal solution found
Dual solved problem
  0 simplex iterations in 0s

Final objective                         : 0.000000000000000e-01
  Max primal violation      (abs / rel) :       0.0 /       0.0
  Max dual violation        (abs / rel) :       0.0 /       0.0
  Max complementarity viol. (abs / rel) :       0.0 /       0.0
All values within tolerances
 *** Search unfinished ***    Time:     0 Nodes:          0
Number of integer feasible solutions found is 0
Best bound is      .000000

Starting root cutting & heuristics

 Its Type    BestSoln    BestBound   Sols    Add    Del     Gap     GInf   Time
*             .000000      .000000      1               0.0e+00        0      0
 *** Search completed ***     Time:     0 Nodes:          1
Number of integer feasible solutions found is 1
Best integer solution found is      .000000
Best bound is      .000000
Uncrunching matrix
Status: Optimal
Solution Written to sudokuout.txt
```
**sudokuout.txt**
```
+-------+-------+-------+
| 5 3 4 | 6 7 8 | 9 1 2 |
| 6 7 2 | 1 9 5 | 3 4 8 |
| 1 9 8 | 3 4 2 | 5 6 7 |
+-------+-------+-------+
| 8 5 9 | 7 6 1 | 4 2 3 |
| 4 2 6 | 8 5 3 | 7 9 1 |
| 7 1 3 | 9 2 4 | 8 5 6 |
+-------+-------+-------+
| 9 6 1 | 5 3 7 | 2 8 4 |
| 2 8 7 | 4 1 9 | 6 3 5 |
| 3 4 5 | 2 8 6 | 1 7 9 |
+-------+-------+-------+
```

### CODE REVIEW

**Comment by fmars** [comment]
@stumitchell I'm trying to adding more parameter support for PuLP to Xpress solver. Please let me know if anything is wrong.

**Comment by fmars** [comment]
btw, if we use whitespace in LpProblem.name, for example "Test Example", and enable keepFiles=1, then  it will crash the program because line 1225. Xpress will think "Test" as file name. 
https://github.com/coin-or/pulp/blob/master/src/pulp/solvers.py#L1225

So I'd like to change one line as 
`self.name = name.replace(" ", "_")`
https://github.com/coin-or/pulp/blob/master/src/pulp/pulp.py#L1109
Please let me know what you think. I can send another request for this.

**Comment by stumitchell** [comment]
Looks good please remove the .DS files, and I should be able to merge

**Comment by fmars** [comment]
oops sorry about that. 
@stumitchell  thanks for reviewing. I have updated it.

**Comment by stumitchell** [comment]
Thanks

**Pull request merged**
