### PR TITLE
The "Infeasible" result by the CPLEX solver is now detected correctly.

### PR DESCRIPTION
**Pull request by progirep**
This was mentioned as a TODO.

### CODE REVIEW

**Comment by pchtsp** [comment]
Hello!

Thanks for the initiative.
Unfortunately, what we wanted is to differentiate between integer feasible
solutions and optimal. Infeasible solutions are already detected by the
lack of solution file.

I’m not sure if CPLEX returns the status for integer feasible but if it
did, we would use it.

For example, in the case of CBC we do the following to detect integer
feasible or optimal solutions (via status and sol_status):

https://github.com/coin-or/pulp/blob/183dbdff3f6a4e559af8d503752c27c95b0c2a00/src/pulp/solvers.py#L1548

Franco

**Comment by progirep** [comment]
I actually ran into the problem that an exception was thrown at line https://github.com/coin-or/pulp/blob/183dbdff3f6a4e559af8d503752c27c95b0c2a00/src/pulp/solvers.py#L550 because CPLEX returned *in the solution file* that there was no solution. The model only utilized real-valued variables. So while you are certainly right that the TODO comment should not be removed, the one-line fix may still make sense to be added.

I'm seeing this behavior with CPLEX 12.8.0.0.

**Comment by pchtsp** [comment]
makes sense. I guess, undo the TODO line and it should be fine.

@stumitchell what do you think?

**Comment by progirep** [comment]
Thanks for your reply. I'm closing this pull request as I've pushed the amended change request to a new pull request: https://github.com/coin-or/pulp/pull/251

**Pull request closed without merging**
