### PR TITLE
Documentation and revised status map in MOSEK-PuLP

### PR DESCRIPTION
**Pull request by Utkarsh-Detha**
- Mosek solution status mosek.solsta.dual_infeas_cer (Dual infeasible certificate) is mapped onto LpStatusUnbounded.
- Descriptions are included into the docstrings for generating the documentation.

Another small change was to replace 4 spaces with a tab in the final line of pulp/doc/Makefile, because I was getting an error due to that.

### CODE REVIEW

**Comment by pchtsp** [comment]
Hello,

For some reason the build in Travis failed; can you check that? 
Also, is there the possibility to use Mosek with an academic license? I'd like to check this integration but I'm not sure if I was able to download the Mosek software and take an academic license that easily.

thanks,

Franco

**Comment by Utkarsh-Detha** [comment]
> Hello,
> 
> For some reason the build in Travis failed; can you check that?
> Also, is there the possibility to use Mosek with an academic license? I'd like to check this integration but I'm not sure if I was able to download the Mosek software and take an academic license that easily.
> 
> thanks,
> 
> Franco

Hi Franco, 

Thank you for your response.

The one job that failed had this to say in its job-log:
`curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out
Unable to download 3.5 archive. The archive may not exist. Please consider a different version.`

I am not very familiar with Travis and its proceedings, so I might be mistaken, but I think this job is failing is because of some unrelated issue. All other python versions seem to be doing fine. Can I request you to run another Travis build (or should I just create another pull request)? I will also continue investigating if these things don't help.

Regarding the license, you can get a personal/institutional academic license
[https://www.mosek.com/products/academic-licenses/](here). You can also get a commercial trial license (if, for example, you are not currently a member of an academic institution).

Thank you.

Regards,
Utkarsh 
Mosek ApS

**Comment by Utkarsh-Detha** [comment]
I made a minuscule commit in order to get Travis to run another build, and it ran fine this time. I hope it can be merged now. 
Regards,
Utkarsh (Mosek ApS)

**Comment by stumitchell** [comment]
@Utkarsh-Detha have you signed a contributors agreement?

https://www.coin-or.org/contributing/code/

https://www.coin-or.org/management/forms/csro.pdf

**Comment by Utkarsh-Detha** [comment]
> @Utkarsh-Detha have you signed a contributors agreement?
> 
> https://www.coin-or.org/contributing/code/
> 
> https://www.coin-or.org/management/forms/csro.pdf

Yes, I had signed the contributor's agreement, as you suggested, when I first made a pull request for PuLP interface for Mosek. Do I need to sign another agreement for the second request?

Regards,
Utkarsh

**Comment by stumitchell** [comment]
@Utkarsh-Detha right sorry, it is hard to keep track of.

@pchtsp please continue looking at this.

**Pull request merged**
